version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017  # MongoDB connection URI

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
